# # Options for analysis running.
run:
  skip-files:
    - pkg/util/logger.go
# output:
#   # See the dedicated "output" documentation section.
#   option: value
# # All available settings of specific linters.
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/ # all github packages
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/stretchr
linters:
  # See the dedicated "linters" documentation section.
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - gomnd
    - godot
    - exhaustruct
    - gofmt
    - gofumpt
    - godox
    - varnamelen
    - revive
    - paralleltest
    - testpackage
    - tagalign
    # are deprecated by authors
    - maligned
    - ifshort
    - golint
    - scopelint
    - interfacer
    - varcheck
    - deadcode
    - nosnakecase
    # are disabled because of generics
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

# issues:
#   # See the dedicated "issues" documentation section.
#   #option: value
# severity:
#   # See the dedicated "severity" documentation section.
#   option: value