
services:
  
  db:
    image: postgres:15.4-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data_minibank
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      UNLEASH_USER: ${UNLEASH_USER}
      UNLEASH_PASSWORD: ${UNLEASH_PASSWORD}
      UNLEASH_DB: ${UNLEASH_DB}
      AUTH_MINIBANK_DB: ${AUTH_MINIBANK_DB}
      AUTH_MINIBANK_USER: ${AUTH_MINIBANK_USER}
      AUTH_MINIBANK_PASSWORD: ${AUTH_MINIBANK_PASSWORD}
      USER_MINIBANK_DB: ${USER_MINIBANK_DB}
      USER_MINIBANK_USER: ${USER_MINIBANK_USER}
      USER_MINIBANK_PASSWORD: ${USER_MINIBANK_PASSWORD}
      ACCOUNT_MINIBANK_DB: ${ACCOUNT_MINIBANK_DB}
      ACCOUNT_MINIBANK_USER: ${ACCOUNT_MINIBANK_USER}
      ACCOUNT_MINIBANK_PASSWORD: ${ACCOUNT_MINIBANK_PASSWORD}
    ports:
      - 5432:5432
    networks:
      minibank_net:
    restart: unless-stopped
    
  adminer:
    image: adminer:4.8.1
    ports:
      - 8002:8080
    networks:
      minibank_net:
    depends_on: 
      - db
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    networks:
      minibank_net:  
    volumes:
    - ./backend/services/auth/internal/migrations:/migrations/auth-minibank
    - ./backend/services/user/internal/migrations:/migrations/user-minibank
    - ./backend/services/account/internal/migrations:/migrations/account-minibank
    command: ["-path", "/migrations/${SERVICE}", "-database",  "postgres://${MINIBANK_USER}:${MINIBANK_PASSWORD}@db:5432/${MINIBANK_DB}?sslmode=disable", "up", "1"]
    depends_on: 
      - db
  
  unleash:
    image: unleashorg/unleash-server
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${UNLEASH_DB}
      DATABASE_PASSWORD: ${UNLEASH_PASSWORD}
      DATABASE_USERNAME: ${UNLEASH_USER}
      DATABASE_SSL: false
    networks:
      minibank_net:
    ports:
      - 4242:4242
    depends_on:
      - db
    restart: unless-stopped

  swagger:    
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    volumes:
      - ./docs:/docs
    environment:
      SWAGGER_JSON: /docs/swagger.json
    ports:
      - 8001:8080
    networks:
      minibank_net:

  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    volumes:
      - /var/log/nginx:/var/log/nginx
     # - /opt/minibank-web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
        - 80:80
    hostname: nginx
    depends_on:
      - db
    networks:
      minibank_net:
    restart: unless-stopped

  web-minibank-blue:
    image: pistollo/web-minibank:${WEB_APP_VERSION}
    container_name: web-minibank-blue
    hostname: web-minibank-blue
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
    volumes:
      - /var/log/web:/var/log/nginx
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/nginx/conf.d:/etc/nginx/conf.d  
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 8888:80
    restart: unless-stopped
  
  web-minibank-green:
    image: pistollo/web-minibank:${WEB_APP_VERSION}
    container_name: web-minibank-blue
    hostname: web-minibank-blue
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
    volumes:
      - /var/log/web:/var/log/nginx
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/nginx/conf.d:/etc/nginx/conf.d  
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 8889:80
    restart: unless-stopped

  account-minibank-blue:
    image: pistollo/account-minibank:${ACCOUNT_APP_VERSION}
    container_name: account-minibank-blue
    hostname: account-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/account/Dockerfile
    environment:
      CONFIG_PATH: ${ACCOUNT_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/account-config.yaml:/etc/minibank/account-config.yaml   
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4464:3333
    restart: unless-stopped

  account-minibank-green:
    image: pistollo/account-minibank:${ACCOUNT_APP_VERSION}
    container_name: account-minibank-green
    hostname: account-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/account/Dockerfile
    environment:
      CONFIG_PATH: ${ACCOUNT_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/account-config.yaml:/etc/minibank/account-config.yaml
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4465:3333
    restart: unless-stopped
  
  auth-minibank-blue:
    image: pistollo/auth-minibank:${AUTH_APP_VERSION}
    container_name: auth-minibank-blue
    hostname: auth-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/auth/Dockerfile
    environment:
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/auth-config.yaml:/etc/minibank/auth-config.yaml   
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4444:3333
    restart: unless-stopped

  auth-minibank-green:
    image: pistollo/auth-minibank:${AUTH_APP_VERSION}
    container_name: auth-minibank-green
    hostname: auth-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/auth/Dockerfile
    environment:
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/auth-config.yaml:/etc/minibank/auth-config.yaml
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4445:3333
    restart: unless-stopped
  
  user-minibank-blue:
    image: pistollo/user-minibank:${USER_APP_VERSION}
    container_name: user-minibank-blue
    hostname: user-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/user/Dockerfile
    environment:
      CONFIG_PATH: ${USER_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/user-config.yaml:/etc/minibank/user-config.yaml   
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4454:3333
    restart: unless-stopped

  user-minibank-green:
    image: pistollo/user-minibank:${USER_APP_VERSION}
    container_name: user-minibank-green
    hostname: user-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/user/Dockerfile
    environment:
      CONFIG_PATH: ${USER_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/user-config.yaml:/etc/minibank/user-config.yaml
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4455:3333
    restart: unless-stopped

  mgmt-minibank-blue:
    image: pistollo/mgmt-minibank:${MGMT_APP_VERSION}
    container_name: mgmt-minibank-blue
    hostname: mgmt-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/mgmt/Dockerfile
    environment:
      CONFIG_PATH: ${MGMT_CONFIG_PATH}
      AUTH_HOST: ${AUTH_HOST}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
      USER_HOST: ${USER_HOST}
      ACCOUNT_HOST: ${ACCOUNT_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/mgmt-config.yaml:/etc/minibank/mgmt-config.yaml   
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4484:3333
    restart: unless-stopped

  mgmt-minibank-green:
    image: pistollo/mgmt-minibank:${MGMT_APP_VERSION}
    container_name: mgmt-minibank-green
    hostname: mgmt-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/mgmt/Dockerfile
    environment:
      CONFIG_PATH: ${MGMT_CONFIG_PATH}
      AUTH_HOST: ${AUTH_HOST}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
      USER_HOST: ${USER_HOST}
      ACCOUNT_HOST: ${ACCOUNT_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/mgmt-config.yaml:/etc/minibank/mgmt-config.yaml
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4485:3333
    restart: unless-stopped

volumes:
  pgdata:

networks:
  minibank_net:
