include:
  - ./compose/compose-db.yml
  - ./compose/compose-unleash.yml
  - ./compose/compose-migrate.yml

services: 

  swagger:    
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    volumes:
      - ./docs:/docs
    environment:
      SWAGGER_JSON: /docs/swagger.json
    ports:
      - 8001:8080
    networks:
      minibank_net:

  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
        - 80:80
    hostname: nginx
    networks:
      minibank_net:
    restart: unless-stopped

  web-minibank-blue:
    image: pistollo/web-minibank:${WEB_APP_VERSION}
    container_name: web-minibank-blue
    hostname: web-minibank-blue
    build: 
      context: .
      dockerfile: ./web/Dockerfile
      args:
        - public_url=${PUBLIC_URL}
        - react_app_url=${REACT_APP_URL}
    volumes:
      - /var/log/web:/var/log/nginx
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      minibank_net:
    ports:
      - 8888:80
    restart: unless-stopped
  
  web-minibank-green:
    image: pistollo/web-minibank:${WEB_APP_VERSION}
    container_name: web-minibank-green
    hostname: web-minibank-green
    build: 
      context: .
      dockerfile: ./web/Dockerfile
      args:
        - public_url=${PUBLIC_URL}
        - react_app_url=${REACT_APP_URL}
    volumes:
      - /var/log/web:/var/log/nginx
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/nginx/conf.d:/etc/nginx/conf.d  
    networks:
      minibank_net:
    ports:
      - 8889:80
    restart: unless-stopped

  uproxy-minibank-blue:
    image: pistollo/uproxy-minibank:${UPROXY_APP_VERSION}
    container_name: uproxy-minibank-blue
    hostname: uproxy-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/uproxy/Dockerfile
    environment:
      CONFIG_PATH: ${UPROXY_CONFIG_PATH}
      UNLEASH_TOGGLES_URL: ${UNLEASH_TOGGLES_URL}
      UNLEASH_ADMIN_TOKEN: ${UNLEASH_ADMIN_TOKEN}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/uproxy-config.yaml:/etc/minibank/uproxy-config.yaml   
    depends_on:
      - unleash
    networks:
      minibank_net:
    ports:
      - 4494:3333
    restart: unless-stopped

  uproxy-minibank-green:
    image: pistollo/uproxy-minibank:${UPROXY_APP_VERSION}
    container_name: uproxy-minibank-green
    hostname: uproxy-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/uproxy/Dockerfile
    environment:
      CONFIG_PATH: ${UPROXY_CONFIG_PATH}
      UNLEASH_TOGGLES_URL: ${UNLEASH_TOGGLES_URL}
      UNLEASH_ADMIN_TOKEN: ${UNLEASH_ADMIN_TOKEN}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/uproxy-config.yaml:/etc/minibank/uproxy-config.yaml
    depends_on:
      - unleash
    networks:
      minibank_net:
    ports:
      - 4495:3333
    restart: unless-stopped

  account-minibank-blue:
    image: pistollo/account-minibank:${ACCOUNT_APP_VERSION}
    container_name: account-minibank-blue
    hostname: account-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/account/Dockerfile
    environment:
      CONFIG_PATH: ${ACCOUNT_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/account-config.yaml:/etc/minibank/account-config.yaml   
    depends_on:
      - db-account-minibank
      - unleash
    networks:
      minibank_net:
    ports:
      - 4464:3333
    restart: unless-stopped

  account-minibank-green:
    image: pistollo/account-minibank:${ACCOUNT_APP_VERSION}
    container_name: account-minibank-green
    hostname: account-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/account/Dockerfile
    environment:
      CONFIG_PATH: ${ACCOUNT_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/account-config.yaml:/etc/minibank/account-config.yaml
    depends_on:
      - db-account-minibank
      - unleash
    networks:
      minibank_net:
    ports:
      - 4465:3333
    restart: unless-stopped
  
  auth-minibank-blue:
    image: pistollo/auth-minibank:${AUTH_APP_VERSION}
    container_name: auth-minibank-blue
    hostname: auth-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/auth/Dockerfile
    environment:
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/auth-config.yaml:/etc/minibank/auth-config.yaml   
    depends_on:
      - db-auth-minibank
      - unleash
    networks:
      minibank_net:
    ports:
      - 4444:3333
    restart: unless-stopped

  auth-minibank-green:
    image: pistollo/auth-minibank:${AUTH_APP_VERSION}
    container_name: auth-minibank-green
    hostname: auth-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/auth/Dockerfile
    environment:
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/auth-config.yaml:/etc/minibank/auth-config.yaml
    depends_on:
      - db-auth-minibank
      - unleash
    networks:
      minibank_net:
    ports:
      - 4445:3333
    restart: unless-stopped
  
  user-minibank-blue:
    image: pistollo/user-minibank:${USER_APP_VERSION}
    container_name: user-minibank-blue
    hostname: user-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/user/Dockerfile
    environment:
      CONFIG_PATH: ${USER_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/user-config.yaml:/etc/minibank/user-config.yaml   
    depends_on:
      - db-user-minibank
      - unleash
    networks:
      minibank_net:
    ports:
      - 4454:3333
    restart: unless-stopped

  user-minibank-green:
    image: pistollo/user-minibank:${USER_APP_VERSION}
    container_name: user-minibank-green
    hostname: user-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/user/Dockerfile
    environment:
      CONFIG_PATH: ${USER_CONFIG_PATH}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/user-config.yaml:/etc/minibank/user-config.yaml
    depends_on:
      - db-user-minibank
      - unleash
    networks:
      minibank_net:
    ports:
      - 4455:3333
    restart: unless-stopped

  mgmt-minibank-blue:
    image: pistollo/mgmt-minibank:${MGMT_APP_VERSION}
    container_name: mgmt-minibank-blue
    hostname: mgmt-minibank-blue
    build: 
      context: .
      dockerfile: ./backend/services/mgmt/Dockerfile
    environment:
      CONFIG_PATH: ${MGMT_CONFIG_PATH}
      AUTH_HOST: ${AUTH_HOST}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
      USER_HOST: ${USER_HOST}
      ACCOUNT_HOST: ${ACCOUNT_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/mgmt-config.yaml:/etc/minibank/mgmt-config.yaml   
    depends_on:
      - unleash
    networks:
      minibank_net:
    ports:
      - 4484:3333
    restart: unless-stopped

  mgmt-minibank-green:
    image: pistollo/mgmt-minibank:${MGMT_APP_VERSION}
    container_name: mgmt-minibank-green
    hostname: mgmt-minibank-green
    build: 
      context: .
      dockerfile: ./backend/services/mgmt/Dockerfile
    environment:
      CONFIG_PATH: ${MGMT_CONFIG_PATH}
      AUTH_HOST: ${AUTH_HOST}
      AUTH_VERIFY_HOST: ${AUTH_VERIFY_HOST}
      USER_HOST: ${USER_HOST}
      ACCOUNT_HOST: ${ACCOUNT_HOST}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/mgmt-config.yaml:/etc/minibank/mgmt-config.yaml
    depends_on:
      - unleash
    networks:
      minibank_net:
    ports:
      - 4485:3333
    restart: unless-stopped


networks:
  minibank_net:
