#конфигурация HTTP-сервера
http_server_app_config:
  addr: ":3333"
  read_timeout: 5s
  write_timeout: 5s
  max_headers_bytes: 1000
  shut_down_time: 5s
  read_header_timeout: 5s
  idle_timeout: 120s

env: "local" #окружение local/prod

#конфигурация логгера
logger_cfgs:
  - encoding: "console"
    output: "stdout"
    level: "debug"
  - encoding: "console"
    output: "stderr"
    level: "error"
  - encoding: "json"
    output: "info.log"
    level: "info"
  - encoding: "json"
    output: "error.log"
    level: "error"

#конфиг postgresql_db_config
postgres_db_config:
  user: "minibank_user"
  password: "minibank_password"
  host: "db"
  port: "5432"
  name: "minibank_db"
  ssl_mode: "disable"

#конфиг unleash сервера
unleash_server_config:
  app_name: "minibank"
  URL: "http://unleash:4242/api/"
  api_token: "*:development.be6360e3b2b14a88bd2aa93c523e4d9a02f1948d82d5f00089c15f11"
