#конфигурация HTTP-сервера
http_server_app_config:
  addr: "0.0.0.0:3333"
  read_timeout: 5s
  write_timeout: 5s
  max_headers_bytes: 1000
  shut_down_time: 5s
  read_header_timeout: 5s
  idle_timeout: 120s

env: "prod" #окружение local/prod

#конфигурация логгера
logger_cfgs:
  - encoding: "console"
    output: "stdout"
    level: "debug"
  - encoding: "console"
    output: "stderr"
    level: "error"
  - encoding: "json"
    output: "info.log"
    level: "info"
  - encoding: "json"
    output: "error.log"
    level: "error"