#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${USER_MINIBANK_USER} WITH PASSWORD '${USER_MINIBANK_PASSWORD}';
    CREATE DATABASE ${USER_MINIBANK_DB} OWNER ${USER_MINIBANK_USER};
EOSQL