#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${UNLEASH_USER} WITH PASSWORD '${UNLEASH_PASSWORD}';
    CREATE DATABASE ${UNLEASH_DB} OWNER ${UNLEASH_USER};
EOSQL