#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${ACCOUNT_MINIBANK_USER} WITH PASSWORD '${ACCOUNT_MINIBANK_PASSWORD}';
    CREATE DATABASE ${ACCOUNT_MINIBANK_DB} OWNER ${ACCOUNT_MINIBANK_USER};
EOSQL