#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${UNLEASH_USER} WITH PASSWORD '${UNLEASH_PASSWORD}';
    CREATE DATABASE ${UNLEASH_DB} OWNER ${UNLEASH_USER};
    CREATE USER ${AUTH_MINIBANK_USER} WITH PASSWORD '${AUTH_MINIBANK_PASSWORD}';
    CREATE DATABASE ${AUTH_MINIBANK_DB} OWNER ${AUTH_MINIBANK_USER};
    CREATE USER ${USER_MINIBANK_USER} WITH PASSWORD '${USER_MINIBANK_PASSWORD}';
    CREATE DATABASE ${USER_MINIBANK_DB} OWNER ${USER_MINIBANK_USER};
    CREATE USER ${ACCOUNT_MINIBANK_USER} WITH PASSWORD '${ACCOUNT_MINIBANK_PASSWORD}';
    CREATE DATABASE ${ACCOUNT_MINIBANK_DB} OWNER ${ACCOUNT_MINIBANK_USER};
EOSQL