services:
  
  user-backend-blue:
    image: pistollo/user-minibank:${USER_APP_VERSION}
    container_name: user-minibank-blue
    hostname: user-minibank-blue
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_PATH: ${USER_CONFIG_PATH}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/user-config.yaml:/etc/minibank/user-config.yaml   
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4454:3333
    restart: unless-stopped

  user-backend-green:
    image: pistollo/user-minibank:${USER_APP_VERSION}
    container_name: user-minibank-green
    hostname: user-minibank-green
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_PATH: ${USER_CONFIG_PATH}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/user-config.yaml:/etc/minibank/user-config.yaml
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4455:3333
    restart: unless-stopped

