services:
  
  auth-backend-blue:
    image: pistollo/auth-minibank:${AUTH_APP_VERSION}
    container_name: auth-minibank-blue
    hostname: auth-minibank-blue
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log 
      - /etc/minibank/auth-config.yaml:/etc/minibank/auth-config.yaml   
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4444:3333
    restart: unless-stopped

  auth-backend-green:
    image: pistollo/auth-minibank:${AUTH_APP_VERSION}
    container_name: auth-minibank-green
    hostname: auth-minibank-green
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_PATH: ${AUTH_CONFIG_PATH}
    volumes:
      - /var/log/minibank/info.log:/app/info.log
      - /var/log/minibank/error.log:/app/error.log
      - /var/log/minibank/debug.log:/app/debug.log
      - /etc/minibank/auth-config.yaml:/etc/minibank/auth-config.yaml
    depends_on:
      - db
      - unleash
    networks:
      minibank_net:
    ports:
      - 4445:3333
    restart: unless-stopped
