basePath: /api/v1
definitions:
  account.AccountCreateRequest:
    properties:
      currency:
        example: "810"
        type: string
      name:
        example: Удачный
        type: string
    type: object
  account.AccountUpdateRequest:
    properties:
      interest_rate:
        example: 0.125
        type: number
      name:
        example: Удачный
        type: string
    type: object
  account.ChangeBalanceRequest:
    properties:
      amount:
        example: 9999.99
        type: number
    type: object
  mapper.Account:
    properties:
      account:
        example: "40817810902007654321"
        type: string
      amount:
        example: 99999.99
        type: number
      created_at:
        example: "2023-09-19T10:58:00.000Z"
        type: string
      currency:
        example: "810"
        type: string
      id:
        example: fdee7aae-f79f-4653-8a16-9207e6805b93
        type: string
      interest_rate:
        example: 0.125
        type: number
      is_active:
        example: true
        type: boolean
      name:
        example: Удачный
        type: string
      updated_at:
        example: "2023-09-19T10:58:00.000Z"
        type: string
      user_id:
        example: fdee7aae-f79f-4653-8a16-9207e6805b93
        type: string
    type: object
  mapper.User:
    properties:
      created_at:
        example: "2023-09-19T10:58:00.000Z"
        type: string
      email:
        example: Ivanych@gmail.com
        type: string
      id:
        example: fdee7aae-f79f-4653-8a16-9207e6805b93
        type: string
      is_active:
        example: true
        type: boolean
      last_name:
        example: Ivanov
        type: string
      name:
        example: Ivan
        type: string
      patronymic:
        example: Ivanych
        type: string
      updated_at:
        example: "2023-09-19T10:58:00.000Z"
        type: string
      username:
        example: Ivanych
        type: string
    type: object
  user.UserCreateRequest:
    properties:
      email:
        example: Ivanych@gmail.com
        type: string
      lastName:
        example: Ivanov
        type: string
      name:
        example: Ivan
        type: string
      password:
        example: mypass
        type: string
      patronymic:
        example: Ivanych
        type: string
      username:
        example: Ivanec
        type: string
    type: object
  user.UserUpdateRequest:
    properties:
      email:
        example: Ivanych@gmail.com
        type: string
      lastName:
        example: Ivanov
        type: string
      name:
        example: Ivan
        type: string
      patronymic:
        example: Ivanych
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: minibank.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: minibank
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the server's health status.
      responses:
        "200":
          description: Service is healthy - Hello from Health Check Handler Endpoint"
            "StatusOK
          schema:
            type: string
        "500":
          description: StatusInternalError
          schema:
            type: string
      summary: Check the health status of the server
      tags:
      - server
  /users:
    get:
      consumes:
      - application/json
      description: Get User ID with credentials.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved User ID
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Get User ID with credentials.
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user unsing the provided details
      parameters:
      - description: User details for creation
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 'A new user has been created with ID: {id}'
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete the user using the provided user ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted user
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Delete user based on the provided ID.
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Fetch the user details using the provided user ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved user details
          schema:
            $ref: '#/definitions/mapper.User'
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Retrieve user details based on the provided ID.
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update the user details using the provided user ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User Update Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated user details
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Update user details based on the provided ID.
      tags:
      - users
  /users/{id}/accounts:
    get:
      consumes:
      - application/json
      description: Fetch the list of accounts using the provided User ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved account details
          schema:
            items:
              $ref: '#/definitions/mapper.Account'
            type: array
        "404":
          description: Accounts not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Retrieve list of accounts based on the provided User ID.
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Create a new account using the provided details
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Account details for creation
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/account.AccountCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 'A new account has been created with number: {string}'
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Create a new account
      tags:
      - accounts
  /users/{userid}/accounts/{id}:
    delete:
      consumes:
      - application/json
      description: Delete the account using the provided account ID.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: path
        name: userid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted account
          schema:
            type: string
        "404":
          description: Account not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Delete account based on the provided ID.
      tags:
      - accounts
    get:
      consumes:
      - application/json
      description: Fetch the account details using the provided account ID.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: path
        name: userid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved account details
          schema:
            $ref: '#/definitions/mapper.Account'
        "404":
          description: Account not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Retrieve account details based on the provided ID.
      tags:
      - accounts
    put:
      consumes:
      - application/json
      description: Update the account details using the provided user ID.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: path
        name: userid
        required: true
        type: string
      - description: Account Update Payload
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.AccountUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated account details
          schema:
            type: string
        "404":
          description: Account not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Update account details based on the provided ID.
      tags:
      - accounts
  /users/{userid}/accounts/{id}/topup:
    put:
      consumes:
      - application/json
      description: TopUp the account balance using the provided user ID and amount.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: path
        name: userid
        required: true
        type: string
      - description: TopUp Account Payload
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.ChangeBalanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully toped up account details
          schema:
            type: string
        "404":
          description: Account not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: TopUp account balance based on the provided ID.
      tags:
      - accounts
  /users/{userid}/accounts/{id}/withdraw:
    put:
      consumes:
      - application/json
      description: Withdraw money using the provided user ID and amount.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: path
        name: userid
        required: true
        type: string
      - description: Withdraw Account Payload
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.ChangeBalanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully Withdrawed account
          schema:
            type: string
        "404":
          description: Account not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Withdraw money based on the provided ID.
      tags:
      - accounts
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
