name: CD user service

on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - 'mini-bank/backend/services/user/**'
      - '.github/workflows/CI-user*'
  workflow_dispatch:
    inputs:
      reason:
        description: "Name the reason"
        default: "Just because"
        required: true
      version:
        description: 'Docker image version'
        required: true
        default: 'latest'
  
jobs:
  build:
    name: Build and push Docker image to Dockerhub
    runs-on: ubuntu-20.04

    steps:
# определяем версию (из пуша или при диспатче)
      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Running workflow_dispatch, version is ${{ github.event.inputs.version }}"
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            TAG_VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
            echo "Running on push to tag, version is $TAG_VERSION"
            echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV
          else
            echo "Unknown event, exiting"
            exit 1
          fi

# заливаем исходники
      - name: Check out code                        
        uses: actions/checkout@v3

# ставим Go
      - name: Setup Go                              
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

# логинимся в докерхаб      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

# собираем образ и пушим в докерхаб      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/services/user/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-minibank:${{ env.VERSION }}
          labels: ${{ secrets.DOCKERHUB_USERNAME }}/user-minibank:${{ env.VERSION }}
  
  deploy:
    needs: build
    name: Deploy 
    runs-on: ubuntu-20.04
    
# коннектимся по SSH,скачиваем образ и запускаем 
    steps:
      - name: SSH connect
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/mini-bank
            git pull
            export USER_CONFIG_PATH=${{ vars.USER_CONFIG_PATH }}
            export USER_APP_VERSION=${{ env.VERSION }}
            echo 'Переменные для миграции'
            export MIGRATE=YES
            export SERVICE=user-minibank
            USER_MINIBANK_DB=${{ secrets.USER_MINIBANK_DB }}
            USER_MINIBANK_USER=${{ secrets.USER_MINIBANK_USER }}
            USER_MINIBANK_PASSWORD=${{ secrets.USER_MINIBANK_PASSWORD }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user-minibank:${{ env.VERSION }}
            /bin/bash deploy.sh
            