name: CD 

on:
  #push:
  #  branches:
  #    - "main"
  #  tags:
  #    - "*.*.*"
  workflow_dispatch:
    inputs:
      reason:
        description: "Name the reason"
        default: "Just because"
        required: true
      version:
        description: 'Docker image version'
        required: true
        default: 'latest'
  
jobs:
  build:
    name: Build and push Docker image to Dockerhub
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: mkdir -p build/; go build -o build/minibank cmd/main.go

      #вывести тег для использования в версии image
      - name: Versioning        
        run: echo "Version is ${{ github.event.inputs.version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pistollo/minibank:${{ github.event.inputs.version }}
          labels: pistollo/minibank:${{ github.event.inputs.version }}
  
  deploy:
    name: Deploy 
    runs-on: ubuntu-20.04
    env:
      CONFIG_PATH: ${{ vars.CONFIG_PATH }}
    steps:
      - name: SSH connect
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/mini-bank
            git pull origin main
            echo "CONFIG_PATH: $CONFIG_PATH"
            docker pull pistollo/minibank:${{ github.event.inputs.version }}
            docker run -e CONFIG_PATH=$CONFIG_PATH pistollo/minibank:${{ github.event.inputs.version }}