name: CD 

on:
  push:
    branches:
      - "main"
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      reason:
        description: "Name the reason"
        default: "Just because"
        required: true
  
jobs:
  build:
    name: Build and push Docker image to Dockerhub
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: mkdir -p build/; go build -o build/minibank cmd/main.go

      #вывести тег для использования в версии image
      - name: Get latest tag
        id: gettag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: pistollo/minibank:${{ steps.gettag.outputs.tag }}