name: CI auth service

on:
  push:
    branches:
      - main
      - develop
      - release/**
    paths:
      - 'backend/services/auth/**'
      - '.github/workflows/CI-auth*'
  pull_request:
    branches:
      - main
      - develop
      - release/**
    paths:
      - 'mini-bank/backend/services/auth/**'
      - '.github/workflows/CI-auth*'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Check out code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: backend/services/auth
          args: ./...

  test:
    needs: lint
    name: Unit test 
    runs-on: ubuntu-20.04    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run go test
        working-directory: backend/services/auth
        run: go test ./... -v --cover

  build:
    needs: test
    name: build 
    runs-on: ubuntu-20.04    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build
        run: |
          cd backend/services/auth
          go build -o build/minibank cmd/main.go