name: CI Mgmt service

on:
  push:
    paths:
      - 'mini-bank/backend/services/mgmt'
  pull_request:
    paths:
      - 'mini-bank/backend/services/mgmt'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Check out code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: backend/services/mgmt
          args: ./...

  test:
    needs: lint
    name: Unit test 
    runs-on: ubuntu-20.04    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run go test
        run: cd backend && go test ./services/mgmt/... -v --cover

  build:
    needs: test
    name: build 
    runs-on: ubuntu-20.04    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build
        run: |
          cd backend/services/mgmt
          go build -o build/minibank

  