name: CI web service

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual run"
        required: true
        default: "Just because"

jobs:
  justJob:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print reason
      run: |
        echo "Workflow run because of: ${{ github.event.inputs.reason }}"
